[package]
name = "iced-incidents"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["svg", "web-colors", "advanced", "debug"] }

[dev-dependencies]
trunk = "0.21.4"
